// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
        
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxuXC053abaVyVK1LcXcrlRXc0MNgqRgk',
    appId: '1:754131155209:web:a922787ed7a677f1023bd8',
    messagingSenderId: '754131155209',
    projectId: 'okookie',
    authDomain: 'okookie.firebaseapp.com',
    storageBucket: 'okookie.firebasestorage.app',
    measurementId: 'G-R9B3CTJ623',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7MPHY_x1nkq32zVfXdorAkoBY02v2o-s',
    appId: '1:754131155209:android:8ead5068c8da3de0023bd8',
    messagingSenderId: '754131155209',
    projectId: 'okookie',
    storageBucket: 'okookie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI29wGDRbUUEOJF26f6c1-0Zfw96ht_RA',
    appId: '1:754131155209:ios:b2eacaee8456ad47023bd8',
    messagingSenderId: '754131155209',
    projectId: 'okookie',
    storageBucket: 'okookie.firebasestorage.app',
    iosBundleId: 'com.example.okookie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI29wGDRbUUEOJF26f6c1-0Zfw96ht_RA',
    appId: '1:754131155209:ios:b2eacaee8456ad47023bd8',
    messagingSenderId: '754131155209',
    projectId: 'okookie',
    storageBucket: 'okookie.firebasestorage.app',
    iosBundleId: 'com.example.okookie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxuXC053abaVyVK1LcXcrlRXc0MNgqRgk',
    appId: '1:754131155209:web:539372beeb60f744023bd8',
    messagingSenderId: '754131155209',
    projectId: 'okookie',
    authDomain: 'okookie.firebaseapp.com',
    storageBucket: 'okookie.firebasestorage.app',
    measurementId: 'G-N9MHCB7FMC',
  );
}
